#!/usr/bin/env bash
# =============================================================================
# setup-cloudwatch-agent.sh
# =============================================================================
# Installs and configures the AWS CloudWatch Agent on Linux servers.
#
# What is CloudWatch?
# ────────────────────
# AWS CloudWatch is AWS's monitoring and observability service. The CloudWatch
# Agent extends its capabilities beyond what's natively monitored:
#
# Without agent:   EC2 CPU, network I/O, disk I/O (hypervisor view)
# With agent:      Memory, disk space, process counts, custom app logs
#
# The agent sends metrics and logs to CloudWatch where you can:
#   - Create dashboards and graphs
#   - Set alarms that trigger when thresholds are breached
#   - Auto-scale based on memory usage
#   - Aggregate logs from multiple servers
#
# Prerequisites:
#   - Running on an EC2 instance (or on-premises with CloudWatch connectivity)
#   - IAM role with CloudWatchAgentServerPolicy attached to the EC2 instance
#   - Or AWS credentials configured (for on-premises servers)
#
# Usage:
#   sudo ./setup-cloudwatch-agent.sh
#   sudo ./setup-cloudwatch-agent.sh --log-group /my-app/logs --log-file /var/log/app.log
#
# Author  : IT-Architect-UK
# Repo    : https://github.com/IT-Architect-UK/monorepo
# Version : 1.0.0
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
log()     { echo -e "${GREEN}[✔]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✘] ERROR:${NC} $*" >&2; exit 1; }
section() { echo -e "\n${BLUE}${BOLD}━━━ $* ━━━${NC}"; }

LOG_GROUP=""; LOG_FILE=""; REGION=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --log-group) LOG_GROUP="$2"; shift 2 ;;
        --log-file)  LOG_FILE="$2";  shift 2 ;;
        --region)    REGION="$2";    shift 2 ;;
        *) error "Unknown option: $1" ;;
    esac
done

[[ $EUID -ne 0 ]] && error "Run as root: sudo $0"

# Auto-detect region from EC2 metadata service if not specified
if [[ -z "$REGION" ]]; then
    REGION=$(curl -s --max-time 3 http://169.254.169.254/latest/meta-data/placement/region 2>/dev/null || echo "")
    [[ -z "$REGION" ]] && REGION="eu-west-2"   # Default fallback
fi

section "AWS CloudWatch Agent Setup"
log "Region: $REGION"

section "1 — Install CloudWatch Agent"
ARCH=$(uname -m)
if [[ "$ARCH" == "x86_64" ]]; then
    PKG_URL="https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
elif [[ "$ARCH" == "aarch64" ]]; then
    PKG_URL="https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/arm64/latest/amazon-cloudwatch-agent.deb"
else
    error "Unsupported architecture: $ARCH"
fi

wget -qO /tmp/amazon-cloudwatch-agent.deb "$PKG_URL"
dpkg -i /tmp/amazon-cloudwatch-agent.deb
rm /tmp/amazon-cloudwatch-agent.deb
log "CloudWatch Agent installed"

section "2 — Create Agent Configuration"
HOSTNAME=$(hostname)
LOG_SECTION=""
if [[ -n "$LOG_FILE" ]]; then
    [[ -z "$LOG_GROUP" ]] && LOG_GROUP="/$HOSTNAME/$(basename "$LOG_FILE")"
    LOG_SECTION='"logs": {
            "logs_collected": {
                "files": {
                    "collect_list": [
                        {
                            "file_path": "'"$LOG_FILE"'",
                            "log_group_name": "'"$LOG_GROUP"'",
                            "log_stream_name": "'"$HOSTNAME"'",
                            "timezone": "UTC"
                        }
                    ]
                }
            }
        },'
fi

cat > /opt/aws/amazon-cloudwatch-agent/bin/config.json << CONFIG
{
    "agent": {
        "metrics_collection_interval": 60,
        "run_as_user": "cwagent"
    },
    "metrics": {
        "namespace": "CWAgent",
        "append_dimensions": {
            "InstanceId": "\${aws:InstanceId}",
            "InstanceType": "\${aws:InstanceType}",
            "AutoScalingGroupName": "\${aws:AutoScalingGroupName}"
        },
        "metrics_collected": {
            "mem": {
                "measurement": ["mem_used_percent", "mem_available_percent"]
            },
            "disk": {
                "measurement": ["disk_used_percent", "disk_free"],
                "resources": ["/", "/var", "/home"],
                "ignore_file_system_types": ["sysfs", "devtmpfs"]
            },
            "netstat": {
                "measurement": ["tcp_established", "tcp_time_wait"]
            },
            "processes": {
                "measurement": ["running", "sleeping", "dead", "zombie"]
            }
        }
    },
    $LOG_SECTION
    "_comment": "Generated by setup-cloudwatch-agent.sh"
}
CONFIG

section "3 — Start Agent"
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
    -a fetch-config \
    -m ec2 \
    -s \
    -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json

log "CloudWatch Agent started and enabled"

section "4 — Verify"
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a status

section "Complete!"
echo ""
log "Metrics will appear in CloudWatch in 1-2 minutes"
echo ""
echo "  View metrics in AWS Console:"
echo "  CloudWatch → Metrics → All metrics → CWAgent → InstanceId"
echo ""
echo "  Useful CloudWatch metrics now available:"
echo "  - mem_used_percent   (Memory usage %)"
echo "  - disk_used_percent  (Disk usage % per mount)"
echo "  - processes_running  (Running process count)"
echo ""
echo "  Create an alarm (example: alert if memory > 85%):"
echo "  aws cloudwatch put-metric-alarm \\"
echo "    --alarm-name 'High-Memory-$HOSTNAME' \\"
echo "    --metric-name mem_used_percent \\"
echo "    --namespace CWAgent \\"
echo "    --statistic Average \\"
echo "    --period 300 \\"
echo "    --threshold 85 \\"
echo "    --comparison-operator GreaterThanThreshold \\"
echo "    --evaluation-periods 2 \\"
echo "    --alarm-actions arn:aws:sns:$REGION:ACCOUNT:TOPIC"
