#!/usr/bin/env bash
# =============================================================================
# provision-ansible-server.sh
#
# PURPOSE
#   Installs Ansible and all dependencies needed to run this repo's playbooks
#   on an Ansible control node VM. Run by Packer after provision.sh has already
#   hardened the base OS.
#
# WHAT IT INSTALLS
#   • Python 3 + pip (via apt)
#   • Ansible (latest stable from the official deadsnakes/ansible PPA)
#   • sshpass  — allows Ansible to authenticate with password if needed
#   • python3-boto3 / python3-botocore — for AWS modules
#   • ansible-galaxy collections:
#       community.general      — hundreds of extra modules
#       community.crypto       — TLS / certificate modules
#       ansible.posix          — file, mount, sysctl modules
#       amazon.aws             — AWS EC2 / S3 modules
#   • A dedicated 'ansible' OS user with sudo NOPASSWD
#   • SSH client config that enables agent forwarding by default
#   • /opt/ansible directory owned by the ansible user
#   • A bootstrap helper script at /opt/ansible/bootstrap-control-node.sh
#
# USAGE
#   This script is called by Packer — you don't run it manually.
#   If you need to run it on an existing server:
#     sudo bash provision-ansible-server.sh
# =============================================================================

set -euo pipefail

ANSIBLE_USER="ansible"
ANSIBLE_HOME="/opt/ansible"
ANSIBLE_SSH_DIR="/home/${ANSIBLE_USER}/.ssh"

echo "=========================================================="
echo " Ansible Control Node Provisioner"
echo " $(date)"
echo "=========================================================="

# ─── 1. System packages ───────────────────────────────────────────────────────
echo ""
echo "[1/7] Installing system packages..."
apt-get update -qq

# software-properties-common gives us add-apt-repository
apt-get install -y --no-install-recommends \
    software-properties-common \
    python3 \
    python3-pip \
    python3-venv \
    python3-boto3 \
    python3-botocore \
    sshpass \
    git \
    curl \
    jq \
    unzip

echo "  ✓ System packages installed"

# ─── 2. Add Ansible PPA and install Ansible ───────────────────────────────────
echo ""
echo "[2/7] Adding Ansible PPA and installing Ansible..."

add-apt-repository --yes --update ppa:ansible/ansible
apt-get install -y ansible

ANSIBLE_VERSION=$(ansible --version | head -1)
echo "  ✓ ${ANSIBLE_VERSION}"

# ─── 3. Install Ansible Galaxy collections ────────────────────────────────────
echo ""
echo "[3/7] Installing Ansible Galaxy collections..."

# Install system-wide so all users benefit
ansible-galaxy collection install \
    community.general \
    community.crypto \
    ansible.posix \
    amazon.aws \
    --force

echo "  ✓ Galaxy collections installed"

# ─── 4. Create the 'ansible' service account ─────────────────────────────────
echo ""
echo "[4/7] Creating '${ANSIBLE_USER}' service account..."

if ! id "${ANSIBLE_USER}" &>/dev/null; then
    useradd \
        --system \
        --shell /bin/bash \
        --create-home \
        --comment "Ansible service account" \
        "${ANSIBLE_USER}"
    echo "  ✓ User '${ANSIBLE_USER}' created"
else
    echo "  · User '${ANSIBLE_USER}' already exists"
fi

# Passwordless sudo — Ansible often needs to escalate on managed hosts
echo "${ANSIBLE_USER} ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/${ANSIBLE_USER}"
chmod 0440 "/etc/sudoers.d/${ANSIBLE_USER}"
echo "  ✓ Passwordless sudo configured"

# ─── 5. SSH configuration for agent forwarding ────────────────────────────────
echo ""
echo "[5/7] Configuring SSH for the ansible user..."

mkdir -p "${ANSIBLE_SSH_DIR}"
chmod 700 "${ANSIBLE_SSH_DIR}"
chown -R "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_SSH_DIR}"

# SSH client config — enables agent forwarding and disables strict host checking
# for private RFC1918 ranges (safe for home lab / internal networks)
cat > "${ANSIBLE_SSH_DIR}/config" << 'SSH_EOF'
# Ansible control node SSH config
# Generated by Packer provision-ansible-server.sh

# ── Global defaults ────────────────────────────────────────────────────────────
Host *
    ServerAliveInterval   60
    ServerAliveCountMax    3
    ConnectTimeout        10
    ControlMaster         auto
    ControlPath           ~/.ssh/cm-%r@%h:%p
    ControlPersist        10m

# ── Home lab / private network ─────────────────────────────────────────────────
# For internal hosts we disable strict host key checking (convenient for home labs
# where hosts are frequently rebuilt). Do NOT use this for internet-facing servers.
Host 10.* 172.16.* 172.17.* 172.18.* 172.19.* 172.20.* 172.21.* 172.22.* 172.23.* 172.24.* 172.25.* 172.26.* 172.27.* 172.28.* 172.29.* 172.30.* 172.31.* 192.168.*
    StrictHostKeyChecking  no
    UserKnownHostsFile     /dev/null
    ForwardAgent           yes

SSH_EOF

chmod 600 "${ANSIBLE_SSH_DIR}/config"
chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_SSH_DIR}/config"
echo "  ✓ SSH config written"

# ─── 6. Set up /opt/ansible workspace ────────────────────────────────────────
echo ""
echo "[6/7] Setting up ${ANSIBLE_HOME} workspace..."

mkdir -p \
    "${ANSIBLE_HOME}/playbooks" \
    "${ANSIBLE_HOME}/roles" \
    "${ANSIBLE_HOME}/inventory" \
    "${ANSIBLE_HOME}/inventory/group_vars" \
    "${ANSIBLE_HOME}/logs"

chown -R "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_HOME}"

# ansible.cfg — placed at /opt/ansible/ansible.cfg so it's picked up when the
# ansible user runs commands from that directory
cat > "${ANSIBLE_HOME}/ansible.cfg" << 'CFG_EOF'
# =============================================================================
# Ansible Configuration — Control Node
# /opt/ansible/ansible.cfg
# =============================================================================
# This file is loaded when you run ansible-playbook from /opt/ansible/
# Override individual settings with environment variables:  ANSIBLE_<SETTING>=value

[defaults]
# Where Ansible looks for your inventory
inventory          = /opt/ansible/inventory/hosts.yml

# Where roles are stored
roles_path         = /opt/ansible/roles

# Log file — rotated by logrotate (config below)
log_path           = /opt/ansible/logs/ansible.log

# SSH settings
remote_user        = ubuntu          # Change to your default server username
private_key_file   = ~/.ssh/id_ed25519
host_key_checking  = False           # Disable for home lab; enable for production

# Performance
forks              = 10              # Run tasks on 10 hosts in parallel
pipelining         = True            # Reduces SSH connections (speeds up playbooks)
gathering          = smart           # Cache facts; re-gather only when needed
fact_caching       = jsonfile
fact_caching_connection = /tmp/ansible_facts_cache
fact_caching_timeout    = 86400      # Cache facts for 24 hours

# Output
stdout_callback    = yaml            # Cleaner output than the default
display_skipped_hosts = False

[privilege_escalation]
become             = True
become_method      = sudo
become_user        = root
become_ask_pass    = False

[ssh_connection]
ssh_args           = -C -o ControlMaster=auto -o ControlPersist=10m
retries            = 3
CFG_EOF

chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_HOME}/ansible.cfg"
echo "  ✓ ansible.cfg written"

# ─── 7. Bootstrap helper script ───────────────────────────────────────────────
echo ""
echo "[7/7] Writing bootstrap helper script..."

cat > "${ANSIBLE_HOME}/bootstrap-control-node.sh" << 'BOOTSTRAP_EOF'
#!/usr/bin/env bash
# =============================================================================
# bootstrap-control-node.sh
#
# Run this ONCE after you first boot the Ansible control node VM.
# It generates an SSH key pair, displays the public key, and shows you how
# to distribute it to managed hosts.
#
# Usage:
#   sudo -u ansible bash /opt/ansible/bootstrap-control-node.sh
# =============================================================================

set -euo pipefail

ANSIBLE_USER="ansible"
SSH_KEY_PATH="/home/${ANSIBLE_USER}/.ssh/id_ed25519"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Ansible Control Node Bootstrap"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Generate SSH key if it doesn't exist ─────────────────────────────────────
if [[ ! -f "${SSH_KEY_PATH}" ]]; then
    echo ""
    echo "[1/3] Generating Ed25519 SSH key pair for the ansible user..."
    sudo -u "${ANSIBLE_USER}" ssh-keygen \
        -t ed25519 \
        -C "ansible-control-node@$(hostname)" \
        -f "${SSH_KEY_PATH}" \
        -N ""
    echo "  ✓ Key pair generated at ${SSH_KEY_PATH}"
else
    echo ""
    echo "[1/3] SSH key already exists at ${SSH_KEY_PATH}"
fi

# ── Show the public key ───────────────────────────────────────────────────────
echo ""
echo "[2/3] Public key (copy this to your managed hosts):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
cat "${SSH_KEY_PATH}.pub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Show how to distribute the key ───────────────────────────────────────────
echo ""
echo "[3/3] How to distribute this key to managed hosts:"
echo ""
echo "  Option A — ssh-copy-id (interactive, one host at a time):"
echo "    sudo -u ansible ssh-copy-id -i ${SSH_KEY_PATH}.pub user@<managed-host>"
echo ""
echo "  Option B — Ansible playbook (distribute to all hosts at once):"
echo "    cd /opt/ansible"
echo "    sudo -u ansible ansible-playbook playbooks/distribute-ssh-key.yml \\"
echo "      -e 'target_hosts=all' \\"
echo "      -k   # prompts for the managed host's password this first time"
echo ""
echo "  Option C — Proxmox cloud-init (paste the public key above into:"
echo "    Proxmox UI → VM → Cloud-Init tab → SSH public key)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Test connectivity after distributing the key:"
echo "  cd /opt/ansible && sudo -u ansible ansible all -m ping"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
BOOTSTRAP_EOF

chmod +x "${ANSIBLE_HOME}/bootstrap-control-node.sh"
chown "${ANSIBLE_USER}:${ANSIBLE_USER}" "${ANSIBLE_HOME}/bootstrap-control-node.sh"
echo "  ✓ Bootstrap script written to ${ANSIBLE_HOME}/bootstrap-control-node.sh"

# ─── Configure logrotate for Ansible logs ────────────────────────────────────
cat > /etc/logrotate.d/ansible << 'LOGROTATE_EOF'
/opt/ansible/logs/ansible.log {
    weekly
    rotate 8
    compress
    missingok
    notifempty
    create 0640 ansible ansible
}
LOGROTATE_EOF
echo "  ✓ logrotate configured"

# ─── Final summary ────────────────────────────────────────────────────────────
echo ""
echo "=========================================================="
echo " Ansible Control Node provisioning complete!"
echo ""
echo " Ansible version : $(ansible --version | head -1)"
echo " Ansible user    : ${ANSIBLE_USER}"
echo " Workspace       : ${ANSIBLE_HOME}"
echo " Config file     : ${ANSIBLE_HOME}/ansible.cfg"
echo " Playbooks       : ${ANSIBLE_HOME}/playbooks/"
echo " Roles           : ${ANSIBLE_HOME}/roles/"
echo " Inventory       : ${ANSIBLE_HOME}/inventory/hosts.yml"
echo ""
echo " After first boot, run:"
echo "   sudo -u ansible bash ${ANSIBLE_HOME}/bootstrap-control-node.sh"
echo "=========================================================="
