#!/usr/bin/env bash
# =============================================================================
# deploy-cert-to-nginx.sh
# =============================================================================
# Deploys an existing TLS certificate to Nginx.
# Use this when you have a certificate from any CA (Let's Encrypt, commercial,
# or your own internal CA) and need to configure Nginx to use it.
#
# Usage:
#   sudo ./deploy-cert-to-nginx.sh \
#     -d example.com \
#     -c /path/to/fullchain.pem \
#     -k /path/to/privkey.pem
#
# Options:
#   -d DOMAIN      Domain name (used for the nginx server_name and config filename)
#   -c CERT        Path to certificate file (fullchain.pem recommended)
#   -k KEY         Path to private key file (privkey.pem)
#   -p PORT        HTTPS port (default: 443)
#   -b BACKEND     Optional backend to proxy to (e.g. http://localhost:3000)
#   -r             Redirect HTTP to HTTPS (default: enabled)
#   -h             Help
#
# Author  : IT-Architect-UK
# Repo    : https://github.com/IT-Architect-UK/monorepo
# Version : 1.0.0
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
log()     { echo -e "${GREEN}[✔]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✘] ERROR:${NC} $*" >&2; exit 1; }
section() { echo -e "\n${BLUE}${BOLD}━━━ $* ━━━${NC}"; }

# ── Load defaults from .env if present ───────────────────────────────────────
ENV_FILE="$(dirname "$0")/../.env"
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE" && log "Loaded defaults from .env"


[[ $EUID -ne 0 ]] && error "Run as root: sudo $0"

DOMAIN=""; CERT=""; KEY=""; PORT=443; BACKEND=""; HTTP_REDIRECT=true

while getopts "d:c:k:p:b:rh" opt; do
    case $opt in
        d) DOMAIN="$OPTARG" ;;
        c) CERT="$OPTARG" ;;
        k) KEY="$OPTARG" ;;
        p) PORT="$OPTARG" ;;
        b) BACKEND="$OPTARG" ;;
        r) HTTP_REDIRECT=true ;;
        h) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) error "Unknown option" ;;
    esac
done

[[ -z "$DOMAIN" ]] && error "Specify domain with -d"
[[ -z "$CERT" ]]   && error "Specify certificate path with -c"
[[ -z "$KEY" ]]    && error "Specify private key path with -k"
[[ ! -f "$CERT" ]] && error "Certificate not found: $CERT"
[[ ! -f "$KEY" ]]  && error "Private key not found: $KEY"

section "Deploy TLS Certificate to Nginx"
log "Domain : $DOMAIN"
log "Cert   : $CERT"
log "Key    : $KEY"
log "Port   : $PORT"

section "1 — Verify Certificate and Key Match"
CERT_MOD=$(openssl x509 -noout -modulus -in "$CERT" | md5sum)
KEY_MOD=$(openssl rsa -noout -modulus -in "$KEY" | md5sum)
[[ "$CERT_MOD" != "$KEY_MOD" ]] && error "Certificate and private key do NOT match. Check you have the right files."
log "Certificate and key match"

section "2 — Install Certificate Files"
CERT_DIR="/etc/ssl/certs/custom"
KEY_DIR="/etc/ssl/private/custom"
mkdir -p "$CERT_DIR" "$KEY_DIR"

install -m 644 "$CERT" "$CERT_DIR/${DOMAIN}.pem"
install -m 600 "$KEY"  "$KEY_DIR/${DOMAIN}.key"
log "Installed to $CERT_DIR and $KEY_DIR"

section "3 — Create Nginx Configuration"
NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}.conf"

if [[ -n "$BACKEND" ]]; then
    # Reverse proxy configuration
    NGINX_LOCATION="
    location / {
        proxy_pass $BACKEND;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }"
else
    # Static file serving
    NGINX_LOCATION="
    root /var/www/${DOMAIN};
    index index.html index.htm;
    location / {
        try_files \$uri \$uri/ =404;
    }"
fi

cat > "$NGINX_CONF" << NGINXEOF
# Nginx configuration for $DOMAIN
# Generated by deploy-cert-to-nginx.sh

server {
    listen $PORT ssl http2;
    listen [::]:$PORT ssl http2;
    server_name $DOMAIN;

    # TLS certificate configuration
    ssl_certificate     $CERT_DIR/${DOMAIN}.pem;
    ssl_certificate_key $KEY_DIR/${DOMAIN}.key;

    # Modern TLS settings (TLS 1.2 and 1.3 only — disables old insecure versions)
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # HSTS: tells browsers to always use HTTPS for this domain
    # WARNING: once set, cannot easily be undone. Test on staging first.
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Other security headers
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy "no-referrer-when-downgrade";
    $NGINX_LOCATION
}
NGINXEOF

# HTTP → HTTPS redirect block
if [[ "$HTTP_REDIRECT" == "true" ]]; then
cat >> "$NGINX_CONF" << REDIRECTEOF

# Redirect all HTTP traffic to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}
REDIRECTEOF
fi

log "Nginx config written to $NGINX_CONF"

section "4 — Enable and Test"
ln -sf "$NGINX_CONF" "/etc/nginx/sites-enabled/${DOMAIN}.conf"

# Test config before reloading — prevents outage if config has errors
nginx -t && log "Nginx config test passed"
systemctl reload nginx && log "Nginx reloaded"

section "Complete!"
log "HTTPS is now serving $DOMAIN on port $PORT"
echo ""
echo "  Test your certificate: https://www.ssllabs.com/ssltest/analyze.html?d=$DOMAIN"
echo "  Config file: $NGINX_CONF"
